<?php

use Vemt\Jasper\Resource\Resource;

/**
 * Test class for Resource.
 * Generated by PHPUnit on 2012-06-04 at 19:49:33.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Resource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Resource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::fromJasperListResponse
     * @todo Implement testFromJasperListResponse().
     */
    public function testFromJasperListResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::hasProperty
     * @todo Implement testHasProperty().
     */
    public function testHasProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getProperties
     * @todo Implement testGetProperties().
     */
    public function testGetProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getId
     * @todo Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setId
     * @todo Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getLabel
     * @todo Implement testGetLabel().
     */
    public function testGetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setLabel
     * @todo Implement testSetLabel().
     */
    public function testSetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getDescription
     * @todo Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setDescription
     * @todo Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getUri
     * @todo Implement testGetUri().
     */
    public function testGetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setUri
     * @todo Implement testSetUri().
     */
    public function testSetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getType
     * @todo Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setType
     * @todo Implement testSetType().
     */
    public function testSetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getCreationDate
     * @todo Implement testGetCreationDate().
     */
    public function testGetCreationDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setCreationDate
     * @todo Implement testSetCreationDate().
     */
    public function testSetCreationDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getIsNew
     * @todo Implement testGetIsNew().
     */
    public function testGetIsNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setIsNew
     * @todo Implement testSetIsNew().
     */
    public function testSetIsNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::__toString
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::setAttachments
     * @todo Implement testSetAttachments().
     */
    public function testSetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::hasAttachments
     * @todo Implement testHasAttachments().
     */
    public function testHasAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vemt\Jasper\Resource\Resource::getAttachments
     * @todo Implement testGetAttachments().
     */
    public function testGetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
